dist: jammy
language: python

matrix:
    include:
        - python: '3.7'
          env:

        - python: '3.8'
          env:

        - python: '3.9'
          env:
            - COVERAGE="true"

        - python: '3.10'
          env:

        - python: '3.11'
          env:
            - CYTHON="true" # numpy source build

        - python: '3.12-dev'
          env:
            - CYTHON="true" # numpy source build

        - python: 'pypy3.7-7.3.9'
          env:

        - python: 'pypy3.8-7.3.9' # at 7.3.11
          env:

        - python: 'pypy3.9-7.3.9' # at 7.3.12
          env:

        - python: 'pypy3.10-7.3.12'
          env:

    allow_failures:
        - python: '3.12-dev'
        - python: 'pypy3.10-7.3.12' # CI missing
    fast_finish: true

cache:
    pip: true

before_install: #NOTE: DISPLAY-related tests don't break build on Travis
    - sudo apt-get -y install xorg openbox grace # DISPLAY=:0.0 xmgrace #Can't open display; Failed initializing GUI, exiting
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $CYTHON == "true" ]]; then pip install "cython<0.29.25"; fi #FIXME

install:
    - python -m pip install .

script:
    - for test in pygrace/tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in pygrace/tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then coverage report; fi
